# Generated by Django 5.2.7 on 2026-06-22 14:08

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("dashboards", "0001_initial"),
        ("datasets", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Widget",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("BAR", "Bar Chart"),
                            ("LINE", "Line Chart"),
                            ("PIE", "Pie Chart"),
                            ("KPI", "Key Performance Indicator"),
                            ("TABLE", "Data Table"),
                        ],
                        max_length=50,
                    ),
                ),
                ("query_config", models.TextField()),
                ("position_x", models.IntegerField(default=0)),
                ("position_y", models.IntegerField(default=0)),
                ("width", models.IntegerField(default=4)),
                ("height", models.IntegerField(default=3)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "dashboard",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="widgets",
                        to="dashboards.dashboard",
                    ),
                ),
                (
                    "dataset",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="widgets",
                        to="datasets.dataset",
                    ),
                ),
            ],
            options={
                "db_table": "widgets",
                "ordering": ["created_at"],
            },
        ),
    ]
