# Generated by Django 5.2.15 on 2026-06-23 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("widgets", "0002_alter_widget_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="widget",
            name="type",
            field=models.CharField(
                choices=[
                    ("BAR", "Bar Chart"),
                    ("LINE", "Line Chart"),
                    ("PIE", "Pie Chart"),
                    ("KPI", "Key Performance Indicator"),
                    ("TABLE", "Data Table"),
                    ("AREA", "Area Chart"),
                    ("DONUT", "Donut Chart"),
                    ("RADAR", "Radar Chart"),
                    ("SCATTER", "Scatter Chart"),
                    ("GAUGE", "Gauge Chart"),
                    ("CUSTOM", "Custom Chart"),
                ],
                max_length=50,
            ),
        ),
    ]
