# Generated by Django 5.2.7 on 2026-06-22 14:08

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Report",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "schedule_cron",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "format",
                    models.CharField(
                        choices=[
                            ("PDF", "PDF Document"),
                            ("EXCEL", "Excel Spreadsheet"),
                        ],
                        max_length=20,
                    ),
                ),
                ("recipients", models.TextField()),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "reports",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ReportHistory",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("RUNNING", "Running"),
                            ("COMPLETED", "Completed"),
                            ("FAILED", "Failed"),
                        ],
                        default="PENDING",
                        max_length=50,
                    ),
                ),
                ("file_path", models.CharField(blank=True, max_length=500, null=True)),
                ("error_message", models.TextField(blank=True, null=True)),
                ("run_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "report_histories",
                "ordering": ["-run_at"],
            },
        ),
    ]
