# Generated by Django 5.2.15 on 2026-06-26 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboards", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="dashboard",
            name="is_shared",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="dashboard",
            name="shared_with",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
